### ISSUE TITLE
fragCounter: error from readChar(): line 924 in fragCounter.R

### ISSUE THREAD

**Issue by chris-kreitzer** [mskilab/fragCounter#10]
Hi all,

Installed FragCounter on my local machine, with all the dependencies.
I tried running your example provided `./frag -b inst/extdata/chr21.bam -d inst/extdata/gcMAP21/ -w 200`, however FragCounter is throwing a warning 
> In readChar(check_gz, 4): text connection used with readChar(), results may be incorrect (and subsequent issues, etc.)

I found that this message may constitute from line 924 `fragCounter.R`, and now I am wondering whether my installation went wrong, or my `samtools` is working incorrect or any other related issue;

Many many thanks for your help!

Best,
chris.

**Comment by mskilab** [comment]
I think this was benign - it's just code to recognize bam vs cram .. in any case have fixed this warning
